USE TaqhiShoppingMall;
GO

INSERT INTO dbo.Products
(ProductID, SKU, ProductName, Category, SubCategory, Description, Perishable, Hazardous, ShelfLifeDays,
 ManufactureDate, ExpiryDate, MinTempC, MaxTempC, MaxRelativeHumidity, MinPressureHpa, MaxPressureHpa,
 LightSensitive, FreezeSensitive, PackagingRequirement, HandlingRequirement, SourceNote)
VALUES
('GROC-001','GROC-001','Fresh Milk 1L','Grocery','Dairy',
 'Refrigerated dairy product.',1,0,7,'2026-09-20','2026-09-27',2,8,70,NULL,NULL,0,1,
 'Food-grade sealed refrigerated packaging.','Maintain cold chain; do not freeze.',
 'DEMO DATA: replace with supplier/manufacturer specification.'),
('FROZ-001','FROZ-001','Frozen Mixed Vegetables 1kg','Grocery','Frozen Foods',
 'Frozen food item.',1,0,365,'2026-01-01','2027-01-01',-25,-18,90,NULL,NULL,0,1,
 'Insulated frozen-food packaging.','Maintain frozen chain; avoid thaw/refreeze.',
 'DEMO DATA: replace with supplier specification.'),
('BAKE-001','BAKE-001','Fresh Bread 400g','Grocery','Bakery',
 'Fresh bakery product.',1,0,5,'2026-09-22','2026-09-27',15,25,70,NULL,NULL,0,0,
 'Clean sealed food packaging.','Keep dry; protect from direct heat and contamination.',
 'DEMO DATA.'),
('COSM-001','COSM-001','Moisturizing Skin Cream 100ml','Beauty','Personal Care',
 'Cosmetic cream.',0,0,730,'2025-10-01','2027-10-01',15,30,65,NULL,NULL,1,0,
 'Original sealed cosmetic packaging; protect from direct sunlight.',
 'Avoid prolonged high heat.',
 'DEMO DATA.'),
('ELEC-001','ELEC-001','LED Desk Lamp','Electronics','Lighting',
 'Electrical lighting product.',0,0,NULL,NULL,NULL,10,40,80,NULL,NULL,0,0,
 'Retail box with protective cushioning.','Keep dry; protect from impact.',
 'DEMO DATA.'),
('HOME-001','HOME-001','Cotton Bedsheet Set','Home','Textiles',
 'Household textile.',0,0,NULL,NULL,NULL,5,45,75,NULL,NULL,0,0,
 'Clean dry packaging.','Keep dry and protected from pests.',
 'DEMO DATA.'),
('TOY-001','TOY-001','Children Toy Set','Kids','Toys',
 'Non-food consumer product.',0,0,NULL,NULL,NULL,5,45,75,NULL,NULL,0,0,
 'Original retail packaging.','Avoid direct heat and moisture.',
 'DEMO DATA.'),
('CHEM-001','CHEM-001','Household Cleaning Liquid 1L','Home Care','Cleaning',
 'Household chemical cleaner. Follow its SDS and label.',0,1,730,'2025-01-01','2027-01-01',
 5,30,70,NULL,NULL,1,0,
 'Leak-resistant chemical packaging with secondary containment.',
 'Keep away from heat, ignition sources and incompatible materials. Follow SDS.',
 'DEMO DATA; actual handling must follow the product SDS.'),
('BABY-001','BABY-001','Baby Formula 400g','Grocery','Baby Food',
 'Infant food product.',1,0,365,'2026-01-01','2027-01-01',15,25,60,NULL,NULL,1,0,
 'Original sealed food packaging.',
 'Protect from heat/moisture; follow label/manufacturer storage instructions.',
 'DEMO DATA; actual label/manufacturer limits prevail.');
GO
